# Generated by Django 6.0.4 on 2026-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Brazil', max_length=64),
            preserve_default=False,
        ),
    ]
